# Generated by Django 4.2 on 2025-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_healthrecord_remove_vitals_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sugar_level',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
